// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common_grpc_api.proto

package common_grpc_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CurrentVersionEnum int32

const (
	CurrentVersionEnum_VERSION_0_1_0 CurrentVersionEnum = 0
)

var CurrentVersionEnum_name = map[int32]string{
	0: "VERSION_0_1_0",
}

var CurrentVersionEnum_value = map[string]int32{
	"VERSION_0_1_0": 0,
}

func (x CurrentVersionEnum) String() string {
	return proto.EnumName(CurrentVersionEnum_name, int32(x))
}

func (CurrentVersionEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1d1cf27cd0969e08, []int{0}
}

type QMLModelTypeToAndFromBackend int32

const (
	QMLModelTypeToAndFromBackend_DomainModel QMLModelTypeToAndFromBackend = 0
	QMLModelTypeToAndFromBackend_PluginModel QMLModelTypeToAndFromBackend = 1
)

var QMLModelTypeToAndFromBackend_name = map[int32]string{
	0: "DomainModel",
	1: "PluginModel",
}

var QMLModelTypeToAndFromBackend_value = map[string]int32{
	"DomainModel": 0,
	"PluginModel": 1,
}

func (x QMLModelTypeToAndFromBackend) String() string {
	return proto.EnumName(QMLModelTypeToAndFromBackend_name, int32(x))
}

func (QMLModelTypeToAndFromBackend) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1d1cf27cd0969e08, []int{1}
}

// Message defining QMLModelTypeToAndFromBackend used
type QMLModelTypeToAndFromBackendMessage struct {
	QMLModelTypeToAndFromBackendType QMLModelTypeToAndFromBackend `protobuf:"varint,1,opt,name=qMLModelTypeToAndFromBackendType,proto3,enum=common_grpc_api.QMLModelTypeToAndFromBackend" json:"qMLModelTypeToAndFromBackendType,omitempty"`
	XXX_NoUnkeyedLiteral             struct{}                     `json:"-"`
	XXX_unrecognized                 []byte                       `json:"-"`
	XXX_sizecache                    int32                        `json:"-"`
}

func (m *QMLModelTypeToAndFromBackendMessage) Reset()         { *m = QMLModelTypeToAndFromBackendMessage{} }
func (m *QMLModelTypeToAndFromBackendMessage) String() string { return proto.CompactTextString(m) }
func (*QMLModelTypeToAndFromBackendMessage) ProtoMessage()    {}
func (*QMLModelTypeToAndFromBackendMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d1cf27cd0969e08, []int{0}
}

func (m *QMLModelTypeToAndFromBackendMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QMLModelTypeToAndFromBackendMessage.Unmarshal(m, b)
}
func (m *QMLModelTypeToAndFromBackendMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QMLModelTypeToAndFromBackendMessage.Marshal(b, m, deterministic)
}
func (m *QMLModelTypeToAndFromBackendMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QMLModelTypeToAndFromBackendMessage.Merge(m, src)
}
func (m *QMLModelTypeToAndFromBackendMessage) XXX_Size() int {
	return xxx_messageInfo_QMLModelTypeToAndFromBackendMessage.Size(m)
}
func (m *QMLModelTypeToAndFromBackendMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_QMLModelTypeToAndFromBackendMessage.DiscardUnknown(m)
}

var xxx_messageInfo_QMLModelTypeToAndFromBackendMessage proto.InternalMessageInfo

func (m *QMLModelTypeToAndFromBackendMessage) GetQMLModelTypeToAndFromBackendType() QMLModelTypeToAndFromBackend {
	if m != nil {
		return m.QMLModelTypeToAndFromBackendType
	}
	return QMLModelTypeToAndFromBackend_DomainModel
}

// Parameter used for Empty inputs
type EmptyParameter struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyParameter) Reset()         { *m = EmptyParameter{} }
func (m *EmptyParameter) String() string { return proto.CompactTextString(m) }
func (*EmptyParameter) ProtoMessage()    {}
func (*EmptyParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d1cf27cd0969e08, []int{1}
}

func (m *EmptyParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyParameter.Unmarshal(m, b)
}
func (m *EmptyParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyParameter.Marshal(b, m, deterministic)
}
func (m *EmptyParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyParameter.Merge(m, src)
}
func (m *EmptyParameter) XXX_Size() int {
	return xxx_messageInfo_EmptyParameter.Size(m)
}
func (m *EmptyParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyParameter.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyParameter proto.InternalMessageInfo

// Ack/Nack- Response message with comment
type AckNackResponse struct {
	Acknack              bool     `protobuf:"varint,1,opt,name=acknack,proto3" json:"acknack,omitempty"`
	Comments             string   `protobuf:"bytes,2,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckNackResponse) Reset()         { *m = AckNackResponse{} }
func (m *AckNackResponse) String() string { return proto.CompactTextString(m) }
func (*AckNackResponse) ProtoMessage()    {}
func (*AckNackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d1cf27cd0969e08, []int{2}
}

func (m *AckNackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckNackResponse.Unmarshal(m, b)
}
func (m *AckNackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckNackResponse.Marshal(b, m, deterministic)
}
func (m *AckNackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckNackResponse.Merge(m, src)
}
func (m *AckNackResponse) XXX_Size() int {
	return xxx_messageInfo_AckNackResponse.Size(m)
}
func (m *AckNackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AckNackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AckNackResponse proto.InternalMessageInfo

func (m *AckNackResponse) GetAcknack() bool {
	if m != nil {
		return m.Acknack
	}
	return false
}

func (m *AckNackResponse) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func init() {
	proto.RegisterEnum("common_grpc_api.CurrentVersionEnum", CurrentVersionEnum_name, CurrentVersionEnum_value)
	proto.RegisterEnum("common_grpc_api.QMLModelTypeToAndFromBackend", QMLModelTypeToAndFromBackend_name, QMLModelTypeToAndFromBackend_value)
	proto.RegisterType((*QMLModelTypeToAndFromBackendMessage)(nil), "common_grpc_api.QMLModelTypeToAndFromBackendMessage")
	proto.RegisterType((*EmptyParameter)(nil), "common_grpc_api.EmptyParameter")
	proto.RegisterType((*AckNackResponse)(nil), "common_grpc_api.AckNackResponse")
}

func init() { proto.RegisterFile("common_grpc_api.proto", fileDescriptor_1d1cf27cd0969e08) }

var fileDescriptor_1d1cf27cd0969e08 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x1b, 0x0f, 0x5a, 0x47, 0x6c, 0xe2, 0x82, 0x10, 0xc4, 0x43, 0x88, 0x07, 0x4b, 0xc1,
	0x52, 0xf5, 0x0f, 0x58, 0x35, 0x8a, 0x60, 0x6a, 0x8d, 0xa5, 0xd7, 0xb0, 0x6e, 0x86, 0x10, 0xd2,
	0xdd, 0x59, 0x77, 0x93, 0x43, 0xfe, 0x8d, 0x3f, 0x55, 0x12, 0xa8, 0x87, 0x1e, 0xd2, 0xe3, 0xfb,
	0x78, 0xbc, 0x79, 0xc3, 0x83, 0x73, 0x41, 0x52, 0x92, 0x4a, 0x73, 0xa3, 0x45, 0xca, 0x75, 0x31,
	0xd5, 0x86, 0x2a, 0x62, 0xee, 0x0e, 0x0e, 0x7f, 0x1d, 0xb8, 0xfa, 0x8c, 0xdf, 0x63, 0xca, 0x70,
	0xb3, 0x6a, 0x34, 0xae, 0x68, 0xae, 0xb2, 0x17, 0x43, 0xf2, 0x91, 0x8b, 0x12, 0x55, 0x16, 0xa3,
	0xb5, 0x3c, 0x47, 0xd6, 0x40, 0xf0, 0xd3, 0x63, 0x6b, 0x99, 0xef, 0x04, 0xce, 0x78, 0x74, 0x77,
	0x33, 0xdd, 0x3d, 0xdd, 0x97, 0x9f, 0xec, 0x8d, 0x0d, 0x3d, 0x18, 0x45, 0x52, 0x57, 0xcd, 0x92,
	0x1b, 0x2e, 0xb1, 0x42, 0x13, 0xbe, 0x82, 0x3b, 0x17, 0xe5, 0x82, 0x8b, 0x32, 0x41, 0xab, 0x49,
	0x59, 0x64, 0x3e, 0x1c, 0x71, 0x51, 0x2a, 0x2e, 0xca, 0xae, 0xc6, 0x30, 0xd9, 0x4a, 0x76, 0x01,
	0xc3, 0xb6, 0x10, 0xaa, 0xca, 0xfa, 0x07, 0x81, 0x33, 0x3e, 0x4e, 0xfe, 0xf5, 0xe4, 0x1a, 0xd8,
	0x53, 0x6d, 0x0c, 0xaa, 0x6a, 0x8d, 0xc6, 0x16, 0xa4, 0x22, 0x55, 0x4b, 0x76, 0x06, 0xa7, 0xeb,
	0x28, 0xf9, 0x7a, 0xfb, 0x58, 0xa4, 0xb3, 0xf4, 0x36, 0x9d, 0x79, 0x83, 0xc9, 0x03, 0x5c, 0xf6,
	0x7d, 0xc1, 0x5c, 0x38, 0x79, 0x26, 0xc9, 0x0b, 0xd5, 0x59, 0xbc, 0x41, 0x0b, 0x96, 0x9b, 0x3a,
	0xdf, 0x02, 0xe7, 0xfb, 0xb0, 0x1b, 0xe0, 0xfe, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x10, 0xcf, 0x76,
	0x90, 0x99, 0x01, 0x00, 0x00,
}
