// Code generated by protoc-gen-go. DO NOT EDIT.
// source: qml_grpc_server.proto

package qml_server_grpc_api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Parameter used for Empty inputs
type EmptyParameter struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyParameter) Reset()         { *m = EmptyParameter{} }
func (m *EmptyParameter) String() string { return proto.CompactTextString(m) }
func (*EmptyParameter) ProtoMessage()    {}
func (*EmptyParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a7182eb9dd55f4, []int{0}
}

func (m *EmptyParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyParameter.Unmarshal(m, b)
}
func (m *EmptyParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyParameter.Marshal(b, m, deterministic)
}
func (m *EmptyParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyParameter.Merge(m, src)
}
func (m *EmptyParameter) XXX_Size() int {
	return xxx_messageInfo_EmptyParameter.Size(m)
}
func (m *EmptyParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyParameter.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyParameter proto.InternalMessageInfo

// Ack/Nack- Response message with comment
type AckNackResponse struct {
	Acknack              bool     `protobuf:"varint,1,opt,name=acknack,proto3" json:"acknack,omitempty"`
	Comments             string   `protobuf:"bytes,2,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckNackResponse) Reset()         { *m = AckNackResponse{} }
func (m *AckNackResponse) String() string { return proto.CompactTextString(m) }
func (*AckNackResponse) ProtoMessage()    {}
func (*AckNackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a7182eb9dd55f4, []int{1}
}

func (m *AckNackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckNackResponse.Unmarshal(m, b)
}
func (m *AckNackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckNackResponse.Marshal(b, m, deterministic)
}
func (m *AckNackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckNackResponse.Merge(m, src)
}
func (m *AckNackResponse) XXX_Size() int {
	return xxx_messageInfo_AckNackResponse.Size(m)
}
func (m *AckNackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AckNackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AckNackResponse proto.InternalMessageInfo

func (m *AckNackResponse) GetAcknack() bool {
	if m != nil {
		return m.Acknack
	}
	return false
}

func (m *AckNackResponse) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

type BackendServerInformation struct {
	BackendServerIp      string   `protobuf:"bytes,1,opt,name=backend_server_ip,json=backendServerIp,proto3" json:"backend_server_ip,omitempty"`
	BackendServerPort    string   `protobuf:"bytes,2,opt,name=backend_server_port,json=backendServerPort,proto3" json:"backend_server_port,omitempty"`
	BackendServerUuid    string   `protobuf:"bytes,3,opt,name=backend_server_uuid,json=backendServerUuid,proto3" json:"backend_server_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackendServerInformation) Reset()         { *m = BackendServerInformation{} }
func (m *BackendServerInformation) String() string { return proto.CompactTextString(m) }
func (*BackendServerInformation) ProtoMessage()    {}
func (*BackendServerInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a7182eb9dd55f4, []int{2}
}

func (m *BackendServerInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendServerInformation.Unmarshal(m, b)
}
func (m *BackendServerInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendServerInformation.Marshal(b, m, deterministic)
}
func (m *BackendServerInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendServerInformation.Merge(m, src)
}
func (m *BackendServerInformation) XXX_Size() int {
	return xxx_messageInfo_BackendServerInformation.Size(m)
}
func (m *BackendServerInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendServerInformation.DiscardUnknown(m)
}

var xxx_messageInfo_BackendServerInformation proto.InternalMessageInfo

func (m *BackendServerInformation) GetBackendServerIp() string {
	if m != nil {
		return m.BackendServerIp
	}
	return ""
}

func (m *BackendServerInformation) GetBackendServerPort() string {
	if m != nil {
		return m.BackendServerPort
	}
	return ""
}

func (m *BackendServerInformation) GetBackendServerUuid() string {
	if m != nil {
		return m.BackendServerUuid
	}
	return ""
}

type SwitchOfBackendRequest struct {
	BackendStatus        string   `protobuf:"bytes,1,opt,name=backendStatus,proto3" json:"backendStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchOfBackendRequest) Reset()         { *m = SwitchOfBackendRequest{} }
func (m *SwitchOfBackendRequest) String() string { return proto.CompactTextString(m) }
func (*SwitchOfBackendRequest) ProtoMessage()    {}
func (*SwitchOfBackendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a7182eb9dd55f4, []int{3}
}

func (m *SwitchOfBackendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchOfBackendRequest.Unmarshal(m, b)
}
func (m *SwitchOfBackendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchOfBackendRequest.Marshal(b, m, deterministic)
}
func (m *SwitchOfBackendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchOfBackendRequest.Merge(m, src)
}
func (m *SwitchOfBackendRequest) XXX_Size() int {
	return xxx_messageInfo_SwitchOfBackendRequest.Size(m)
}
func (m *SwitchOfBackendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchOfBackendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchOfBackendRequest proto.InternalMessageInfo

func (m *SwitchOfBackendRequest) GetBackendStatus() string {
	if m != nil {
		return m.BackendStatus
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyParameter)(nil), "qml_server_grpc_api.EmptyParameter")
	proto.RegisterType((*AckNackResponse)(nil), "qml_server_grpc_api.AckNackResponse")
	proto.RegisterType((*BackendServerInformation)(nil), "qml_server_grpc_api.BackendServerInformation")
	proto.RegisterType((*SwitchOfBackendRequest)(nil), "qml_server_grpc_api.SwitchOfBackendRequest")
}

func init() { proto.RegisterFile("qml_grpc_server.proto", fileDescriptor_f4a7182eb9dd55f4) }

var fileDescriptor_f4a7182eb9dd55f4 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x4d, 0x05, 0x6d, 0x07, 0xb4, 0x76, 0x8b, 0x12, 0x7b, 0x2a, 0xa1, 0x42, 0x51, 0xcc,
	0x41, 0xef, 0x82, 0x82, 0x96, 0x5e, 0x6c, 0x4d, 0xf5, 0x5c, 0xb6, 0x9b, 0xad, 0x2e, 0xe9, 0xfe,
	0xe9, 0xee, 0x44, 0xe9, 0xc5, 0x8b, 0xef, 0xe2, 0x73, 0x4a, 0xd2, 0x46, 0x48, 0x89, 0xe0, 0x71,
	0x66, 0x7e, 0x3b, 0xf3, 0xcd, 0x37, 0x0b, 0xc7, 0x4b, 0xb9, 0x98, 0xbe, 0x5a, 0xc3, 0xa6, 0x8e,
	0xdb, 0x77, 0x6e, 0x43, 0x63, 0x35, 0x6a, 0xd2, 0xce, 0xd2, 0xeb, 0xcc, 0xba, 0x4a, 0x8d, 0x08,
	0x8e, 0xe0, 0xf0, 0x5e, 0x1a, 0x5c, 0x8d, 0xa9, 0xa5, 0x92, 0x23, 0xb7, 0xc1, 0x00, 0x9a, 0xb7,
	0x2c, 0x79, 0xa4, 0x2c, 0x89, 0xb8, 0x33, 0x5a, 0x39, 0x4e, 0x7c, 0xd8, 0xa7, 0x2c, 0x51, 0x94,
	0x25, 0xbe, 0xd7, 0xf5, 0xfa, 0xf5, 0xa8, 0x08, 0x49, 0x07, 0xea, 0x4c, 0x4b, 0xc9, 0x15, 0x3a,
	0xbf, 0xd6, 0xf5, 0xfa, 0x8d, 0xe8, 0x37, 0x0e, 0xbe, 0x3d, 0xf0, 0xef, 0x28, 0x4b, 0xb8, 0x8a,
	0x27, 0xf9, 0xd4, 0xa1, 0x9a, 0x6b, 0x2b, 0x29, 0x0a, 0xad, 0xc8, 0x39, 0xb4, 0x66, 0xeb, 0x5a,
	0x21, 0x49, 0x98, 0xbc, 0x79, 0x23, 0x6a, 0xce, 0x4a, 0x8f, 0x0c, 0x09, 0xa1, 0xbd, 0xc5, 0x1a,
	0x6d, 0x71, 0x33, 0xaf, 0x55, 0xa2, 0xc7, 0xda, 0x62, 0x05, 0x9f, 0xa6, 0x22, 0xf6, 0x77, 0x2b,
	0xf8, 0x97, 0x54, 0xc4, 0xc1, 0x0d, 0x9c, 0x4c, 0x3e, 0x04, 0xb2, 0xb7, 0xd1, 0x7c, 0xa3, 0x37,
	0xe2, 0xcb, 0x94, 0x3b, 0x24, 0x3d, 0x38, 0x28, 0x70, 0xa4, 0x98, 0xba, 0x8d, 0xc2, 0x72, 0xf2,
	0xea, 0xab, 0x06, 0xcd, 0x27, 0xb9, 0x18, 0x58, 0xc3, 0xb2, 0xae, 0x82, 0x71, 0x47, 0x3e, 0xe1,
	0xec, 0x99, 0x3b, 0x1c, 0x2a, 0x87, 0x36, 0x65, 0xd9, 0xca, 0x65, 0x2b, 0xc6, 0x54, 0xc5, 0xb9,
	0xd8, 0xcb, 0xb0, 0xe2, 0x2c, 0xe1, 0x5f, 0xbe, 0x75, 0x7a, 0x95, 0xf8, 0xd6, 0xc1, 0x82, 0x1d,
	0x62, 0xe0, 0x74, 0xa4, 0x16, 0xab, 0x07, 0x6d, 0x33, 0x19, 0xe5, 0xf5, 0xc8, 0x45, 0x65, 0x93,
	0x6a, 0x0f, 0xfe, 0x3b, 0x71, 0xb6, 0x97, 0xff, 0xb2, 0xeb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x6d, 0x8d, 0x95, 0xf1, 0x7e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QmlGrpcServicesClient is the client API for QmlGrpcServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QmlGrpcServicesClient interface {
	// Main coordinator sends task to worker with this service
	TestInstructionBackendServerIPandPort(ctx context.Context, in *BackendServerInformation, opts ...grpc.CallOption) (*AckNackResponse, error)
	// OnlyForTestSwitchOfBacken(
	OnlyForTestSwitchOfBacken(ctx context.Context, in *SwitchOfBackendRequest, opts ...grpc.CallOption) (*AckNackResponse, error)
}

type qmlGrpcServicesClient struct {
	cc *grpc.ClientConn
}

func NewQmlGrpcServicesClient(cc *grpc.ClientConn) QmlGrpcServicesClient {
	return &qmlGrpcServicesClient{cc}
}

func (c *qmlGrpcServicesClient) TestInstructionBackendServerIPandPort(ctx context.Context, in *BackendServerInformation, opts ...grpc.CallOption) (*AckNackResponse, error) {
	out := new(AckNackResponse)
	err := c.cc.Invoke(ctx, "/qml_server_grpc_api.QmlGrpcServices/TestInstructionBackendServerIPandPort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qmlGrpcServicesClient) OnlyForTestSwitchOfBacken(ctx context.Context, in *SwitchOfBackendRequest, opts ...grpc.CallOption) (*AckNackResponse, error) {
	out := new(AckNackResponse)
	err := c.cc.Invoke(ctx, "/qml_server_grpc_api.QmlGrpcServices/OnlyForTestSwitchOfBacken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QmlGrpcServicesServer is the server API for QmlGrpcServices service.
type QmlGrpcServicesServer interface {
	// Main coordinator sends task to worker with this service
	TestInstructionBackendServerIPandPort(context.Context, *BackendServerInformation) (*AckNackResponse, error)
	// OnlyForTestSwitchOfBacken(
	OnlyForTestSwitchOfBacken(context.Context, *SwitchOfBackendRequest) (*AckNackResponse, error)
}

// UnimplementedQmlGrpcServicesServer can be embedded to have forward compatible implementations.
type UnimplementedQmlGrpcServicesServer struct {
}

func (*UnimplementedQmlGrpcServicesServer) TestInstructionBackendServerIPandPort(ctx context.Context, req *BackendServerInformation) (*AckNackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestInstructionBackendServerIPandPort not implemented")
}
func (*UnimplementedQmlGrpcServicesServer) OnlyForTestSwitchOfBacken(ctx context.Context, req *SwitchOfBackendRequest) (*AckNackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnlyForTestSwitchOfBacken not implemented")
}

func RegisterQmlGrpcServicesServer(s *grpc.Server, srv QmlGrpcServicesServer) {
	s.RegisterService(&_QmlGrpcServices_serviceDesc, srv)
}

func _QmlGrpcServices_TestInstructionBackendServerIPandPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackendServerInformation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QmlGrpcServicesServer).TestInstructionBackendServerIPandPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qml_server_grpc_api.QmlGrpcServices/TestInstructionBackendServerIPandPort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QmlGrpcServicesServer).TestInstructionBackendServerIPandPort(ctx, req.(*BackendServerInformation))
	}
	return interceptor(ctx, in, info, handler)
}

func _QmlGrpcServices_OnlyForTestSwitchOfBacken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchOfBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QmlGrpcServicesServer).OnlyForTestSwitchOfBacken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qml_server_grpc_api.QmlGrpcServices/OnlyForTestSwitchOfBacken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QmlGrpcServicesServer).OnlyForTestSwitchOfBacken(ctx, req.(*SwitchOfBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _QmlGrpcServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qml_server_grpc_api.QmlGrpcServices",
	HandlerType: (*QmlGrpcServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestInstructionBackendServerIPandPort",
			Handler:    _QmlGrpcServices_TestInstructionBackendServerIPandPort_Handler,
		},
		{
			MethodName: "OnlyForTestSwitchOfBacken",
			Handler:    _QmlGrpcServices_OnlyForTestSwitchOfBacken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qml_grpc_server.proto",
}
