// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mother_server.proto

package mother_server_grpc_api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Ack/Nack- Response message with comment
type AckNackResponse struct {
	Acknack              bool     `protobuf:"varint,1,opt,name=acknack,proto3" json:"acknack,omitempty"`
	Comments             string   `protobuf:"bytes,2,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckNackResponse) Reset()         { *m = AckNackResponse{} }
func (m *AckNackResponse) String() string { return proto.CompactTextString(m) }
func (*AckNackResponse) ProtoMessage()    {}
func (*AckNackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77899df19b225584, []int{0}
}

func (m *AckNackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckNackResponse.Unmarshal(m, b)
}
func (m *AckNackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckNackResponse.Marshal(b, m, deterministic)
}
func (m *AckNackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckNackResponse.Merge(m, src)
}
func (m *AckNackResponse) XXX_Size() int {
	return xxx_messageInfo_AckNackResponse.Size(m)
}
func (m *AckNackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AckNackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AckNackResponse proto.InternalMessageInfo

func (m *AckNackResponse) GetAcknack() bool {
	if m != nil {
		return m.Acknack
	}
	return false
}

func (m *AckNackResponse) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

type WorkerInformation struct {
	WorkerIp             string   `protobuf:"bytes,1,opt,name=worker_ip,json=workerIp,proto3" json:"worker_ip,omitempty"`
	WorkerPort           string   `protobuf:"bytes,2,opt,name=worker_port,json=workerPort,proto3" json:"worker_port,omitempty"`
	WorkerUuid           string   `protobuf:"bytes,3,opt,name=worker_uuid,json=workerUuid,proto3" json:"worker_uuid,omitempty"`
	WorkerTaskUuid       string   `protobuf:"bytes,4,opt,name=worker_task_uuid,json=workerTaskUuid,proto3" json:"worker_task_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkerInformation) Reset()         { *m = WorkerInformation{} }
func (m *WorkerInformation) String() string { return proto.CompactTextString(m) }
func (*WorkerInformation) ProtoMessage()    {}
func (*WorkerInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_77899df19b225584, []int{1}
}

func (m *WorkerInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerInformation.Unmarshal(m, b)
}
func (m *WorkerInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerInformation.Marshal(b, m, deterministic)
}
func (m *WorkerInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerInformation.Merge(m, src)
}
func (m *WorkerInformation) XXX_Size() int {
	return xxx_messageInfo_WorkerInformation.Size(m)
}
func (m *WorkerInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerInformation.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerInformation proto.InternalMessageInfo

func (m *WorkerInformation) GetWorkerIp() string {
	if m != nil {
		return m.WorkerIp
	}
	return ""
}

func (m *WorkerInformation) GetWorkerPort() string {
	if m != nil {
		return m.WorkerPort
	}
	return ""
}

func (m *WorkerInformation) GetWorkerUuid() string {
	if m != nil {
		return m.WorkerUuid
	}
	return ""
}

func (m *WorkerInformation) GetWorkerTaskUuid() string {
	if m != nil {
		return m.WorkerTaskUuid
	}
	return ""
}

func init() {
	proto.RegisterType((*AckNackResponse)(nil), "mother_server_grpc_api.AckNackResponse")
	proto.RegisterType((*WorkerInformation)(nil), "mother_server_grpc_api.WorkerInformation")
}

func init() { proto.RegisterFile("mother_server.proto", fileDescriptor_77899df19b225584) }

var fileDescriptor_77899df19b225584 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x86, 0xad, 0x8a, 0xb6, 0xa3, 0xf8, 0x11, 0x41, 0xca, 0x7a, 0x70, 0xe9, 0xc5, 0x7a, 0xe9,
	0x41, 0x7f, 0x81, 0x27, 0xe9, 0x41, 0x59, 0xaa, 0xe2, 0xb1, 0xc4, 0x34, 0x6a, 0x08, 0xcd, 0x84,
	0x49, 0xaa, 0xf8, 0x5f, 0xfc, 0xb1, 0xb2, 0x49, 0x5d, 0xd6, 0x8f, 0x3d, 0xce, 0x93, 0x87, 0x37,
	0xc9, 0x3b, 0x70, 0xd4, 0xa3, 0x7f, 0x95, 0xd4, 0x3a, 0x49, 0x6f, 0x92, 0x2a, 0x4b, 0xe8, 0x91,
	0x1d, 0xff, 0x80, 0xed, 0x0b, 0x59, 0xd1, 0x72, 0xab, 0x8a, 0x6b, 0xd8, 0xbf, 0x12, 0xfa, 0x96,
	0x0b, 0xdd, 0x48, 0x67, 0xd1, 0x38, 0xc9, 0x72, 0xd8, 0xe6, 0x42, 0x1b, 0x2e, 0x74, 0x9e, 0x4c,
	0x93, 0x32, 0x6d, 0xbe, 0x47, 0x36, 0x81, 0x54, 0x60, 0xdf, 0x4b, 0xe3, 0x5d, 0xbe, 0x3e, 0x4d,
	0xca, 0xac, 0x59, 0xcc, 0xc5, 0x67, 0x02, 0x87, 0x8f, 0x48, 0x5a, 0x52, 0x6d, 0x9e, 0x91, 0x7a,
	0xee, 0x15, 0x1a, 0x76, 0x02, 0xd9, 0x7b, 0x80, 0xad, 0xb2, 0x21, 0x2d, 0x6b, 0xd2, 0x08, 0x6a,
	0xcb, 0x4e, 0x61, 0x67, 0x3c, 0xb4, 0x48, 0x7e, 0x4c, 0x84, 0x88, 0x66, 0x48, 0x7e, 0x49, 0x18,
	0x06, 0xd5, 0xe5, 0x1b, 0xcb, 0xc2, 0xc3, 0xa0, 0x3a, 0x56, 0xc2, 0xc1, 0x28, 0x78, 0xee, 0x74,
	0xb4, 0x36, 0x83, 0xb5, 0x17, 0xf9, 0x3d, 0x77, 0x7a, 0x6e, 0x5e, 0x7c, 0xc0, 0xee, 0x4d, 0x68,
	0xe0, 0x2e, 0x14, 0xc0, 0xd4, 0xe2, 0xb5, 0x33, 0x6e, 0xba, 0xf9, 0x6d, 0xb5, 0x63, 0xe7, 0xd5,
	0xff, 0x2d, 0x55, 0x7f, 0x3e, 0x36, 0x39, 0x5b, 0xa5, 0xfe, 0x6a, 0xb3, 0x58, 0x7b, 0xda, 0x0a,
	0x1b, 0xb8, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x95, 0x8c, 0xa9, 0x1a, 0x98, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MotherServerClient is the client API for MotherServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MotherServerClient interface {
	//Main coordinator sends task to worker with this service
	WorkerIPandPortIs(ctx context.Context, in *WorkerInformation, opts ...grpc.CallOption) (*AckNackResponse, error)
}

type motherServerClient struct {
	cc *grpc.ClientConn
}

func NewMotherServerClient(cc *grpc.ClientConn) MotherServerClient {
	return &motherServerClient{cc}
}

func (c *motherServerClient) WorkerIPandPortIs(ctx context.Context, in *WorkerInformation, opts ...grpc.CallOption) (*AckNackResponse, error) {
	out := new(AckNackResponse)
	err := c.cc.Invoke(ctx, "/mother_server_grpc_api.MotherServer/WorkerIPandPortIs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MotherServerServer is the server API for MotherServer service.
type MotherServerServer interface {
	//Main coordinator sends task to worker with this service
	WorkerIPandPortIs(context.Context, *WorkerInformation) (*AckNackResponse, error)
}

// UnimplementedMotherServerServer can be embedded to have forward compatible implementations.
type UnimplementedMotherServerServer struct {
}

func (*UnimplementedMotherServerServer) WorkerIPandPortIs(ctx context.Context, req *WorkerInformation) (*AckNackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WorkerIPandPortIs not implemented")
}

func RegisterMotherServerServer(s *grpc.Server, srv MotherServerServer) {
	s.RegisterService(&_MotherServer_serviceDesc, srv)
}

func _MotherServer_WorkerIPandPortIs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerInformation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MotherServerServer).WorkerIPandPortIs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mother_server_grpc_api.MotherServer/WorkerIPandPortIs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MotherServerServer).WorkerIPandPortIs(ctx, req.(*WorkerInformation))
	}
	return interceptor(ctx, in, info, handler)
}

var _MotherServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mother_server_grpc_api.MotherServer",
	HandlerType: (*MotherServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WorkerIPandPortIs",
			Handler:    _MotherServer_WorkerIPandPortIs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mother_server.proto",
}
